src/Actinoids/Modlr/RestOdm/Metadata/Driver/YamlFileDriver.php
src/Actinoids/Modlr/RestOdm/Models/Attributes.php
src/Actinoids/Modlr/RestOdm/Models/Model.php
src/Actinoids/Modlr/RestOdm/Models/State.php
src/Actinoids/Modlr/RestOdm/Persister/MongoDBPersister.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterException.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterInterface.php
src/Actinoids/Modlr/RestOdm/Persister/Record.php
src/Actinoids/Modlr/RestOdm/Store/Store.php
src/Actinoids/Modlr/RestOdm/Store/StoreException.php

The "power" of the model has now been moved into the model itself. The store is now database agnostic, and relies on a persister. 
This functionality will also allow us to use models natively in PHP, not just via REST.

Initial Refactor of Model/Store Handling

---

src/Actinoids/Modlr/RestOdm/Models/Attributes.php
src/Actinoids/Modlr/RestOdm/Models/Model.php
src/Actinoids/Modlr/RestOdm/Models/State.php
src/Actinoids/Modlr/RestOdm/Persister/MongoDBPersister.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterInterface.php
src/Actinoids/Modlr/RestOdm/Store/Store.php

Full CRUD is now operational for attributes at the persistence/store level under the new Model/Store structure.

Create, delete, and update support.

---

src/Actinoids/Modlr/RestOdm/Persister/MongoDBPersister.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterInterface.php
src/Actinoids/Modlr/RestOdm/Store/Store.php

Hydrating records from MongoDB were not properly switching the metadata types. This has been resolved by requiring the Store to be passed to all() and retrieve() in the Persister.

Fix polymorphism issue from persistence layer

---

src/Actinoids/Modlr/RestOdm/Metadata/Driver/AbstractFileDriver.php
src/Actinoids/Modlr/RestOdm/Metadata/Driver/DriverInterface.php
src/Actinoids/Modlr/RestOdm/Metadata/Driver/YamlFileDriver.php
src/Actinoids/Modlr/RestOdm/Metadata/EntityMetadata.php
src/Actinoids/Modlr/RestOdm/Metadata/Interfaces/AttributeInterface.php
src/Actinoids/Modlr/RestOdm/Metadata/Interfaces/MergeableInterface.php
src/Actinoids/Modlr/RestOdm/Metadata/Interfaces/PersistenceInterface.php
src/Actinoids/Modlr/RestOdm/Metadata/Interfaces/PersistenceMetadataFactoryInterface.php
src/Actinoids/Modlr/RestOdm/Metadata/MetadataFactory.php
src/Actinoids/Modlr/RestOdm/Persister/MongoDBPersister.php
src/Actinoids/Modlr/RestOdm/Persister/MongoDb/PersistenceMetadata.php
src/Actinoids/Modlr/RestOdm/Persister/MongoDb/PersistenceMetadataFactory.php
src/Actinoids/Modlr/RestOdm/Persister/MongoDb/Persister.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterException.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterInterface.php
src/Actinoids/Modlr/RestOdm/Persister/PersisterManager.php
src/Actinoids/Modlr/RestOdm/Store/Store.php
src/Actinoids/Modlr/RestOdm/Util/EntityUtility.php

MongoDB is still the default persister, but Modlr now supports additional persistence engines.
Metadata handling has been updated to reflect this, as well as the Store's ```getPersisterFor``` method.
This is made possible via the ```PersisterManager``` service that support registering multiple persisters. 
The persister is now responsible for returning a Persistence Metadata Factory to create new instances, handle additional MF load functions, and validate the persistence metadata instances - since these processes will be unique for each persistence engine.
MongoDB persistence classes have now been "bundled" under the MongoDb namespace.

Abstracted Persistence Layer to Support Multiple Persisters

---

src/Actinoids/Modlr/RestOdm/Metadata/AttributeMetadata.php
src/Actinoids/Modlr/RestOdm/Metadata/Driver/YamlFileDriver.php
src/Actinoids/Modlr/RestOdm/Metadata/EntityMetadata.php
src/Actinoids/Modlr/RestOdm/Models/Model.php

Default values can now be set at the entity/model level, or per attribute.
The YAML driver has been updated to support this via ```[modelTypeKey].entity.defaultValues.[attrKey]: [attrValue]``` and ```[modelTypeKey].attributes.[attrKey].defaultValue: [attrValue]```

Added support for model and attribute default values

---

src/Actinoids/Modlr/RestOdm/Metadata/AttributeMetadata.php
src/Actinoids/Modlr/RestOdm/Metadata/Driver/YamlFileDriver.php
src/Actinoids/Modlr/RestOdm/Models/Model.php
src/Actinoids/Modlr/RestOdm/Util/EntityUtility.php

Models can now have calculated attributes. A calculated attribute is one whose value is not persisted, and is calculated using values from other attributes and/or relationships on the Model.
This is accomplished by setting a class name and callback method. When the attribute is accessed, this method will be called to generate the value. The method must be set as ```static``` in the owning class, and must handle one argument: ```Model $model```
The YAML metadata driver supports this by setting ```class``` and ```method``` under ```[modelTypeKey].attributes.[attrKey].calculated```

Added support for calculated attributes

---

src/Rest/RestConfiguration.php
src/Util/EntityUtility.php

Array (collection) and object (hash) attributes are no longer blocked.
Originally, object attributes were going to be treated as "embedded" models. This will no longer be the case, and objects will be treated as a plain-old associative array. Embedded attributes will be handled separately. 
Closes #31

Remove block for array and object attr types

---

src/Metadata/Driver/YamlFileDriver.php
src/Metadata/FieldMetadata.php
src/Models/Model.php

Properties (attributes and relationships) can now be marked as save = false. This prevents the property from being stored by the storage layer.
Closes #27

Add not saved properties

---

src/Models/Model.php
src/Version.php

A model's default attribute value was overwriting a set value. This ensures that if an attribute value has been specifically set, the default value is not applied.

Hotfix: greedy default values

---

src/Metadata/Driver/YamlFileDriver.php
src/Metadata/EntityMetadata.php
src/Metadata/Interfaces/StorageMetadataFactoryInterface.php
src/Metadata/MetadataFactory.php
src/Store/Store.php

- Search and persistence specific properties were being set by the root driver - this should not have been the case. Instead, each sub-library should handle it's own loading. This addresses that concern.
- Add a check for the existence of search in `EntityMetadata`, as this is optional
- Ensure the `Store` checks for enabled search for a `Model`
- Clean up `EntityMetadata` class

Move persister and search specific metadata loading

---

src/Api/AbstractAdapter.php
src/Api/AdapterInterface.php
src/Metadata/EntityMetadata.php
src/Persister/PersisterInterface.php
src/Store/Store.php

The core interfaces and the `Store` now supports querying for Models based on a set of criteria.

Add core query support

---

src/DataTypes/Types/BooleanType.php
src/Version.php

Passing a string of true or false will ensure the value is loaded as a boolean true/false.

Ensure true/false strings use bool equivelant

---

composer.json

This PR bumps the hard version constraint to support either the 2.6+ series or 3.0+ of symfony/http-foundation.

Support Symfony3 modules

---

src/Store/Store.php

Allows access to `MetadataFactory::getAllTypeNames()` (which is already public) from outside the `Store` itself.
Allows external perspective into what model types have been loaded/are available.

Add method to Store to get all available types

---

src/Metadata/Events.php
src/Metadata/Events/MetadataArguments.php
src/Metadata/MetadataFactory.php
src/Version.php

Dispatches a `postLoad` event within the `MetadataFactory` to allow event subscribers to make modifications to `EntityMetadata` before it is cached -- for example, to modify the database name as needed by the application.

Dispatch postLoad metadata event

---

src/Metadata/Events.php
src/Metadata/MetadataFactory.php
src/Version.php

postLoad was already in use by the store.

Changed metadata event name to prevent conflict

---

src/Store/Store.php
src/Version.php

The `loadCollection` method must return an array of Models. If the collection was empty, the code was previously returning the passed collection, and not returning an array.

Fix bug loadCollection was not returning array

---

src/Store/Events.php
src/Store/Events/PreQueryArguments.php
src/Store/Store.php
src/Version.php

The `Store` will now fire a `preQuery` event in `findQuery` before performing the query. This allows event subscribers to manipulate the provided query criteria before sending the request to the persister.

Add support for preQuery events

---

src/Models/Properties.php
src/Version.php

Previously, DateTime objects were not properly being compared due to timezone differences. Using the DateTime timestamp will correct this.

Ensure datetimes are evaluated using timestamp

---

src/Metadata/Driver/YamlFileDriver.php
src/Version.php

Any embeds defined on a mixin were not being applied to the mixin metadata and, due to that, not applied to the model.

Ensure embeds are applied from mixin definitions

---

src/Metadata/Driver/YamlFileDriver.php
src/Util/EntityUtility.php
src/Version.php

If an embed were to reference itself, the YAML driver and validator would be get "stuck" in an infinite loop when loading the metadata for the embed.
Example:
```yaml
foo:
embeds:
someEmbed:
type: one
entity: some-embed
```
```yaml
some-embed:
embeds:
someEmbed:
type: one
entity: some-embed
```
Because the `some-embed` entity was referencing itself, the metadata loading process would infinitely recurse. This has been corrected.

Prevent infinite recursion of self-referencing embeds

---

src/Models/Properties.php
src/Version.php

Using `===` on `\stdClass` values was too strict. This was causing any model with an `object` attribute type to be reporting as dirty, even when it wasn't.

Ensure object property changes are tracked

---

src/Rest/RestRequest.php

If a PHP script (framework/etc) is located under a subdirectory rather than at the root of a domain, PHP's handling of the global request variables gets weird. Specifically, the request_uri is correct, but should have the prefix of script_uri removed from it. This PR allows the modlr API to work if there is a prefix in place.
@zarathustra323 I thought about doing this in as3io/As3ModlrBundle when it is configuring the RestConfiguration in DI, but it unfortunately won't have knowledge of this condition since it's at run-time and not available in the CLI when the cache is generated.
For a concrete example:
A Symfony project is installed at `https://my.domain.com/cool-project`, configured with a `rest_endpoint` of `/api/1.0`.
A request to …

Support prefixes of the REST endpoint

---

src/Store/Store.php

The `getState()->is('dirty')` method only updates when changes are made directly to the owning model, and does not recognize changes made on ancestor embedded models. The `isDirty()` check, however, does not have this problem because it actively introspects ancestor embeds via `hasOneEmbeds->areDirty()` and `hasManyEmbeds->areDirty()`.
As such, the `Store` needs to use this method when determining when to update the model, otherwise changes to ancestor embeds may not be committed.

Rely on model's `isDirty()` over `getState()`
